#!/usr/bin/python3
def safe_print_list(my_list=[], x=0):
    index = 0
    counter = 0
    while(counter < x):
        try:
            print(my_list[index], end = "")
            counter += 1
            index += 1
        except IndexError:
            break
        if counter == x:
            break
    print()
    return counter
